version: '3.7'

services:
  nginx:
    container_name: nginx
    networks: 
      - my_network
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - "WordPress:/var/www/wordpress"
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    networks:
      - my_network
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - "DB:/var/lib/mysql"
    restart: always

  wordpress:
    container_name: wordpress
    networks:
      - my_network
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - "WordPress:/var/www/wordpress"
    depends_on:
      - mariadb
    restart: always

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      -  my_network
    restart: always

  website:
    container_name: website
    build:
      context: ./requirements/bonus/static_website
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
    restart: always


networks:
  my_network:
    driver: bridge

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      device: "/Users/afanti/data/mariadb/"
      o: bind
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: "/Users/afanti/data/wordpress/"
      o: bind

